export type IoniconsName =
    | 'add' | 'add-circle' | 'airplane' | 'alarm'
    | 'albums' | 'alert' | 'american-football'
    | 'analytics' | 'aperture' | 'apps'
    | 'archive' | 'arrow-back' | 'arrow-down'
    | 'arrow-forward' | 'arrow-up' | 'at'
    | 'attach' | 'backspace' | 'barcode'
    | 'baseball' | 'basket' | 'basketball'
    | 'battery-charging' | 'battery-dead'
    | 'battery-full' | 'battery-half'
    | 'beaker' | 'beer' | 'bicycle'
    | 'bluetooth' | 'boat' | 'body'
    | 'bonfire' | 'book' | 'bookmark'
    | 'bookmarks' | 'briefcase' | 'build'
    | 'bulb' | 'bus' | 'business'
    | 'cafe' | 'calculator' | 'calendar'
    | 'call' | 'camera' | 'car'
    | 'card' | 'cart' | 'cash'
    | 'cellular' | 'chatbubbles' | 'checkmark'
    | 'chevron-back' | 'chevron-down'
    | 'chevron-forward' | 'chevron-up'
    | 'clipboard' | 'close' | 'cloud'
    | 'cloudy' | 'code' | 'cog'
    | 'color-fill' | 'color-filter' | 'color-palette'
    | 'color-wand' | 'compass' | 'construct'
    | 'contact' | 'contacts' | 'contract'
    | 'contrast' | 'copy' | 'create'
    | 'crop' | 'cube' | 'cut'
    | 'desktop' | 'disc' | 'document'
    | 'done-all' | 'download' | 'easel'
    | 'egg' | 'exit' | 'expand'
    | 'eye' | 'eye-off' | 'fast-food'
    | 'female' | 'file-tray' | 'film'
    | 'filter' | 'finger-print' | 'fitness'
    | 'flag' | 'flame' | 'flash'
    | 'flashlight' | 'flask' | 'flower'
    | 'folder' | 'folder-open' | 'football'
    | 'funnel' | 'game-controller' | 'gift'
    | 'git-branch' | 'git-commit' | 'git-compare'
    | 'git-merge' | 'git-network' | 'git-pull-request'
    | 'glasses' | 'globe' | 'grid'
    | 'hammer' | 'hand-left' | 'hand-right'
    | 'happy' | 'hardware-chip' | 'headset'
    | 'heart' | 'heart-circle' | 'heart-dislike'
    | 'heart-half' | 'help' | 'help-buoy'
    | 'home' | 'hourglass' | 'ice-cream'
    | 'image' | 'images' | 'infinite'
    | 'information' | 'journal' | 'key'
    | 'keypad' | 'language' | 'laptop'
    | 'layers' | 'leaf' | 'library'
    | 'link' | 'list' | 'locate'
    | 'location' | 'lock-closed' | 'lock-open'
    | 'log-in' | 'log-out' | 'magnet'
    | 'mail' | 'mail-open' | 'male'
    | 'man' | 'map' | 'medal'
    | 'medical' | 'medkit' | 'megaphone'
    | 'menu' | 'mic' | 'mic-off'
    | 'moon' | 'move' | 'musical-note'
    | 'musical-notes' | 'navigate' | 'newspaper'
    | 'notifications' | 'notifications-off'
    | 'nuclear' | 'nutrition' | 'open'
    | 'options' | 'paper-plane' | 'partly-sunny'
    | 'pause' | 'paw' | 'pencil'
    | 'people' | 'person' | 'person-add'
    | 'phone-landscape' | 'phone-portrait'
    | 'pie-chart' | 'pin' | 'pint'
    | 'pizza' | 'planet' | 'play'
    | 'play-back' | 'play-forward' | 'podium'
    | 'power' | 'pricetag' | 'pricetags'
    | 'print' | 'pulse' | 'push'
    | 'qr-code' | 'radio' | 'rainy'
    | 'reader' | 'receipt' | 'recording'
    | 'refresh' | 'reload' | 'remove'
    | 'reorder' | 'repeat' | 'resize'
    | 'restaurant' | 'return-left' | 'return-right'
    | 'reverse-camera' | 'rewind' | 'ribbon'
    | 'rocket' | 'rose' | 'sad'
    | 'save' | 'school' | 'search'
    | 'send' | 'settings' | 'share'
    | 'shield' | 'shirt' | 'shuffle'
    | 'skull' | 'snow' | 'speedometer'
    | 'square' | 'star' | 'stats-chart'
    | 'stop' | 'stopwatch' | 'storefront'
    | 'subway' | 'sunny' | 'swap-horizontal'
    | 'swap-vertical' | 'sync' | 'tablet-landscape'
    | 'tablet-portrait' | 'tennisball' | 'text'
    | 'thermometer' | 'thumbs-down' | 'thumbs-up'
    | 'thunderstorm' | 'time' | 'timer'
    | 'today' | 'train' | 'transgender'
    | 'trash' | 'trending-down' | 'trending-up'
    | 'triangle' | 'trophy' | 'tv'
    | 'umbrella' | 'videocam' | 'volume-high'
    | 'volume-low' | 'volume-medium' | 'volume-mute'
    | 'volume-off' | 'walk' | 'wallet'
    | 'warning' | 'watch' | 'water'
    | 'wifi' | 'woman';